const knowledgeBase = {
  "hola": "¡Hola! Soy tu Fontanero Virtual. ¿En qué puedo ayudarte?",
  "necesito un termo": "Disponemos de Termo 50L y Termo Digital. ¿Cuál te interesa?",
  "fuga": "Si tienes una fuga, revisa juntas y válvulas. Si persiste, llama a un técnico.",
  "calefacción": "Revisa la presión de la caldera y los radiadores para problemas de calefacción.",
  "fontanero urgente": "Tenemos servicio 24h. Llama al +34 612345678.",
  "grifo cocina": "Tenemos grifos de acero inoxidable y con sistema de filtrado de agua.",
  "bañera ducha": "Ofrecemos bañeras de hidromasaje y duchas de alto caudal.",
  "tuberías": "¿Problema con tuberías? Podemos revisar PVC, cobre y multicapa.",
  "desagüe atascado": "Usa un desatascador primero. Si no funciona, puede ser necesario un desatascador profesional.",
  "termostato": "El termostato debe estar conectado correctamente a la caldera.",
  "caldera": "Verifica la presión y el nivel de agua de la caldera.",
  "radiador frío": "Purgar el radiador suele solucionar este problema.",
  "grifo gota": "Asegúrate de apretar bien la arandela y la válvula.",
  "fontanería exterior": "Podemos instalar grifos de jardín y tuberías exteriores resistentes al frío.",
  "agua caliente": "Si no hay agua caliente, revisa el termo o la caldera.",
  "filtro agua": "Ofrecemos filtros de agua para cocina y ducha.",
  "instalación baño": "Podemos instalar lavabo, inodoro y ducha.",
  "reparación inodoro": "Verifica el mecanismo de descarga y la válvula de llenado.",
  "cisterna": "La cisterna puede tener fugas por el mecanismo de descarga o juntas dañadas.",
  "pérdida presión": "Revisa válvulas y filtros, pueden estar obstruidos.",
  "llave paso agua": "Ubica la llave de paso general para cortar agua si hay fuga.",
  "ducha filtrante": "Disponemos de duchas con filtros de impurezas y cal.",
  "termo eléctrico": "Para darte un presupuesto exacto, envíame una foto por WhatsApp y te daré la valoración detallada.",
  "reparar grifo": "Ajusta las piezas internas o reemplaza cartucho si es necesario.",
  "mantenimiento caldera": "Se recomienda limpieza anual y revisión de quemadores.",
  "tuberías congeladas": "Descongela con cuidado usando agua tibia o secador.",
  "presión agua baja": "Comprueba el regulador de presión y grifos obstruidos.",
  "bañera antideslizante": "Ofrecemos instalación de láminas antideslizantes.",
  "revisión mensual": "Chequea juntas, filtros y válvulas cada mes para evitar problemas.",
  "desagüe cocina": "Limpia restos y usa desatascador si es necesario.",
  "ducha termosensible": "Instalamos duchas con control de temperatura constante.",
  "lavabo": "Disponemos de lavabos modernos y clásicos.",
  "grifería": "Tenemos grifería de distintos diseños y materiales.",
  "mangueras": "Revisar mangueras flexibles en lavadoras y lavavajillas.",
  "sifón": "Asegúrate de que el sifón esté bien colocado para evitar malos olores.",
  "válvula seguridad": "Comprueba la válvula de seguridad del termo.",
  "agua fría": "Si no hay agua fría, revisa la entrada principal y filtros.",
  "bañera": "Podemos instalar bañeras de distintos tamaños y materiales.",
  "ducha": "Duchas con teleducha, efecto lluvia y alta presión.",
  "grifo lavabo": "Instalación y reparación de grifos para lavabo.",
  "fontanería cocina": "Instalación de fregaderos, grifos y lavavajillas.",
  "fugas techo": "Si hay fuga en techo, revisa tuberías superiores y juntas.",
  "tubería rota": "Reemplazo de tuberías PVC, cobre y multicapa.",
  "problema caldera": "Verifica códigos de error y llama a un técnico certificado.",
  "presión alta": "Puede necesitar regulador o purgado de radiadores.",
  "termómetro agua": "Instalación de termómetros en tuberías para control de temperatura.",
  "válvula mezcladora": "Ajusta temperatura y presión del agua en duchas.",
  "lavavajillas": "Revisar conexión de agua y desagüe.",
  "filtro ducha": "Reemplazo de filtros según el uso y dureza del agua.",
  "termómetro radiador": "Instalación para medir temperatura de cada radiador.",
  "agua marrón": "Puede ser óxido en tuberías o trabajos recientes.",
  "tubería filtrante": "Instalación de tuberías con filtro interno para agua potable."
};
